language: node_js
node_js:
  - "stable"
install: ./travis-install.sh
script: ./gulp dist && ./gulp links
notifications:
  recipients:
    - geirarne@gmail.com
    - arve.seljebu@gmail.com
addons:
  apt_packages:
    - pandoc
cache:
  directories:
    - node_modules
